### ISSUE TITLE
qq登陆挂了

### ISSUE THREAD

**Issue by xinwii** [erickguan/discourse-chinese-localization-pack#10]
比如 https://meta.discoursecn.org 这个网站的qq登陆挂了

**Comment by martincz** [comment]
Oops! That page doesn’t exist or is private.
是的，挂掉了

**Comment by ghost** [comment]
似乎是弃坑了？

**Comment by martincz** [comment]
@ZackXu0 作者的其它repo看起来还在更新。。。

**Comment by VegaMonika** [comment]
好可惜现在已经没人在开发了
