### ISSUE TITLE
分享微博图标缺失，生成二维码服务失效

### ISSUE THREAD

**Issue by scavin** [erickguan/discourse-chinese-localization-pack#9]
<img width="712" alt="2019-02-19 5 03 20" src="https://user-images.githubusercontent.com/716584/53002726-58a59300-3468-11e9-8602-0af8b59ed68a.png">
<img width="840" alt="2019-02-19 5 03 15" src="https://user-images.githubusercontent.com/716584/53002728-593e2980-3468-11e9-85e3-30eab6824ee1.png">

微博和微信的图标都缺失了，以及 jiathis 似乎死掉了

**Comment by erickguan** [comment]
我也不知道怎么加 svg icon...

**Comment by erickguan** [comment]
找到了，找个时间加进去。https://github.com/discourse/discourse/commit/47cbfb14989bcf828c66b211827cb9355214e71a

**Comment by scavin** [comment]
类似这种么 https://icons8.com/icon/set/weibo/windows

**Comment by erickguan** [comment]
这是二进制图像。现在用的是 SVG 图片了。

**Comment by scavin** [comment]
另外，微博的分享链接没有 https，以及微信的分享服务挂了

**Comment by erickguan** [comment]
微信分享可能得拿掉了。腾讯的 API 要给公众号信息

**Comment by scavin** [comment]
分享到微信不就是把当前页面 URL 生成二维码？然后扫码就可以了呀

**Comment by erickguan** [comment]
这个现在由主题做了，不用插件做了
